import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LoginPage from './loginPage'
// import { getServerSession } from "next-auth/next"
// import { authOptions } from './api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Music-ly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={[styles.description]}>
          <p>
            <code className={styles.code}>
              Music-ly</code> &nbsp; A music search app for all your favorite Artists.
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/logo192.png"
                alt="Pamiam Logo"
                className={styles.vercelLogo}
                width={50}
                height={50}
                priority
              />
            </a>
          </div>
        </div>
        {/* 
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div> */}
        <section className="grid place-items-center">
          <LoginPage />
        </section>
        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Artists <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about your favorite Artist and their&nbsp;music.
            </p>
          </a>

          <a
            href="http://open.spotify.com/track/6rqhFgbbKwnb9MLmUQDhG6"
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Albums <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find the album, make your playlist, enjoy the&nbsp;music!
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Tracks <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover or follow recommendations for each&nbsp;track.
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Tools <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              If your a musician, check out this&nbsp;Metronome.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

// export async function getServerSideProps({ req, res }) {
//   return {
//     props: {
//       session: await getServerSession(req, res, authOptions)
//     }
//   }
// }